site_name: Muchili's Blog
site_url: https://muchili-code.github.io/
use_directory_urls: false  # 禁用目录级 URL，使文件索引方式与 typora 一致
site_author: 慕迟离
site_description: Welcome To my site!

# 在页眉显示GitHub仓库链接
repo_url: https://github.com/Muchili-code/muchili-code.github.io # 博客仓库的实际URL
repo_name: Muchili/Blog # 自定义显示的仓库名称

theme:
  name: material
  custom_dir: overrides 
  language: zh 
  favicon: images/kuma.png

  palette: 
    - media: "(prefers-color-scheme: light)" 
      scheme: default # 主题配色方案
      primary: white # 主色调
      toggle: 
        icon: material/weather-night 
        name: 切换到深色模式                  

    - media: "(prefers-color-scheme: dark)"  
      scheme: slate                           
      primary: black
      toggle:
        icon: material/weather-sunny 
        name: 切换到浅色模式         

  features:
    - navigation.tracking   # 在url中使用标题定位锚点，即追踪当前页面位置，自动更新浏览器URL
    #- navigation.path      # 显示当前路径
    - navigation.prune     # 侧边栏自动折叠，会使得侧边栏只显示当前页面所属的章节及其直接子页面
    - navigation.tabs       # 启用顶级导航为标签页样式，注意顶级导航的概念
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.top        
    - navigation.footer     
    #- navigation.instant    
    #- navigation.sections  
    - navigation.expand     
    - navigation.indexes   #启用节索引页后，可以将文档直接附加到节

    - search.highlight      
    - search.suggest        

    - content.code.annotate # 代码行号
    - content.code.copy     
    - content.tabs          # 允许在 Markdown 中创建选项卡

    #- toc.follow            # toc 跟随
    #- toc.integrate
    - toggle.scheme         # 启用主题切换
  # toc: 
  #  depth: 4
  font:
    text: JetBrains Mono, LXGW WenKai Screen GB Screen
    code: JetBrains Mono, Consolas


copyright: Copyright &copy; 2025 Muchili/All Rights Reserved. 

extra:
  generator: false          # 删除页脚的“使用 MkDocs Material制造”
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Muchili-code/Muchili-code.github.io
      title: 我的Github主页 
    - icon: fontawesome/brands/bilibili 
      link: https://space.bilibili.com/3493125026744857?spm_id_from=333.1387.0.0
    - icon: custom/cc98 
    # D:\Program Files (x86)\Python\python-3.12.10\Lib\site-packages\material\templates\.icons是默认的图标目录，容易出错；此外其寻找方式以自己为根目录
      link: https://www.cc98.org/ 
      title: CC98 论坛 
    - icon: fontawesome/solid/paper-plane 
      link: mailto:<2979568058@qq.com> 
      title: 联系我 
  repo:
    provider: github
    host: github.com
    user: Muchili     
    name: Blog        
  repo_stats: true    # 启用星标和 Fork 数量显示
  alternate:  # 翻译功能
    - name: 中文
      link: "#zh"   
      lang: zh
    - name: English
      link: "#en"   
      lang: en

extra_css:
  - css/card.css
  #- css/code.css
  - css/custom.css
  #- css/counter.css
  - css/header.css
  #- css/palette.css
  - css/sidebar.css
  - css/timeline.css
  - css/extra.css
  - css/adaptation.css
  - css/extra_changelog.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  - https://unpkg.com/katex@0/dist/katex.min.css  # katex样式
  - https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.css
  
extra_javascript:
  - javascripts/anchor.js
  #- javascripts/code.js
  - javascripts/custom.js
  - javascripts/extra.js
  - javascripts/katex.js 
  - javascripts/toc.js 
  - javascripts/typed_init.js
  #- javascripts/typed.js
  - https://cdn.jsdelivr.net/npm/typed.js@2.0.11
  - https://unpkg.com/katex@0/dist/katex.min.js # KaTeX 核心 JS
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js # auto-render 扩展
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

markdown_extensions:

  - abbr                  # 启用缩写功能。
  - attr_list             # 属性列表。允许你为 Markdown 元素（如标题、段落、图片等）添加 HTML 属性。
  - md_in_html            
  - meta                  
  - def_list              
  - footnotes             
  - tables                
  - toc:                  
      permalink: ⚓︎       # 标题的链接（锚点），图标是⚓︎
      title: 目录         
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # Unicode link
      toc_depth: 2-6

  - pymdownx.mark         
  - pymdownx.caret        # 插入文本标记。
  - pymdownx.tilde        # 删除线
  - pymdownx.arithmatex:  # LaTeX 数学公式支持。
      generic: true    
      smart_dollar: false 
      block_tag: 'div'    
  - pymdownx.escapeall 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic       # 评论标记。支持插入、删除、替换等标记，常用于文档审阅
  - pymdownx.keys         # 键盘按键显示。允许你以美观的方式显示键盘按键。
  - pymdownx.tasklist:    
      custom_checkbox: true 

  - admonition            
  #- markdown_gfm_admonition 
  - pymdownx.details      
  - pymdownx.tabbed:      
      alternate_style: true 

  - pymdownx.highlight:   # 代码块高亮
      anchor_linenums: true # 当显示行号时，为每行代码生成一个锚点。
      linenums: true      # 代码块左侧行号
      #auto_title: true    # 自动在代码块上方显示编程语言的名称
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.snippets     # 其他文件作为“代码片段”嵌入到当前文件中。参见 https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
  - sane_lists  # 让列表解析逻辑更符合直觉
  - pymdownx.superfences:  # 增强型代码块
      preserve_tabs: false 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  

plugins:
  - awesome-pages
  - callouts:
      aliases: false
  - changelog
  - glightbox
  #- macros
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      fallback_to_build_date: true
  - statistics:
      words_per_minute: 200
      codelines_per_minute: 80
      page_template: "assets/template.html"

validation:
  nav:
    omitted_files: ignore  # 告诉 MkDocs：没写进 nav 的文件不要报警告

nav:
  - 🏠主页: 
    - index.md 
    #- Home: index.md   

  - 🔖标签:
    - Tag/tag.md

  - 🤖人工智能:
    - Artificial Intelligent/index.md
    - AI 客户端:
      - AI 客户端应用介绍: Artificial Intelligent/AI Desktop Use/quick-start.md 
      - AI 客户端应用的使用: Artificial Intelligent/AI Desktop Use/installation.md
    - GitHub Pages网站搭建指导:
      - Git命令行的使用: Artificial Intelligent/GitHub Pages Instruction/Git命令行.md
      - Git追踪: Artificial Intelligent/GitHub Pages Instruction/Git追踪原理.md
      - 仓库作子模块: Artificial Intelligent/GitHub Pages Instruction/仓库作为子模块.md
      - 项目文件大纲: Artificial Intelligent/GitHub Pages Instruction/项目文件大纲.md

  - 📕College 2: # 这个路径是相对于你的主仓库的 docs/ 目录的
    - indices/College2/index.md
    - 数据结构与算法分析: 
      - indices/College2/DS/index.md
      - 0.进阶语法知识: "notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/0.基础语法知识.md"
      - 1.绪论: "notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/1.绪论.md"
      - 2.线性表: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/2.线性表.md
      - 3.栈和队列: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/3.栈和队列.md
      - 4.串: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/4.串.md
      - 5.数组和广义表: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/5.数组和广义表.md
      - 6.树: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/6.树.md
      - 7.图: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记//7.图/7.图.md
      - 9.查找: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/9.查找.md
      - 10.排序: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/10.排序.md
      - 总复习: notes/College 2/2.数据结构与算法分析（FDS）-Fundemental Data Structure/期末复习/自己笔记/总复习.md

  - 📚College 3:
    - indices/College3/index.md

    - 医学成像: 
      - indices/College3/Medical_Imaging/index.md
      - CT: notes/College 3/1.生物医学成像技术/期末复习/1.XRayCT/XRayCT.md
      - PET: notes/College 3/1.生物医学成像技术/期末复习/PET.md
      - US: notes/College 3/1.生物医学成像技术/期末复习/超声习题.md
      - Optics: notes/College 3/1.生物医学成像技术/期末复习/光学.md
      - MRI: notes/College 3/1.生物医学成像技术/期末复习/5. MRI/MRI.md

    - 嵌入式系统:
      - indices/College3/Embedded systems/index.md
      - 1.导论: notes/College 3/1.嵌入式系统/自己笔记/1-导论.md
      - 2.处理器设计导论: notes/College 3/1.嵌入式系统/自己笔记/2-处理器设计导论.md
      - 3.ARM体系结构: notes/College 3/1.嵌入式系统/自己笔记/3-ARM体系结构.md
      - 4.ARM编程模型: notes/College 3/1.嵌入式系统/自己笔记/4-ARM编程模型.md
      - 5.汇编语言编程: notes/College 3/1.嵌入式系统/自己笔记/5-ARM汇编语言编程.md
      - 6.ARM流水线组织: notes/College 3/1.嵌入式系统/自己笔记/6-ARM流水线组织.md
      - 7.ARM指令集: notes/College 3/1.嵌入式系统/自己笔记/7-ARM指令集.md
      - 10.ARM存储器接口及AMBA总线: notes/College 3/1.嵌入式系统/自己笔记/10-ARM存储器接口及AMBA总线.md
      - 13.ARM-JTAG测试与调试结构: notes/College 3/1.嵌入式系统/自己笔记/13-ARM-JTAG测试与调试结构.md
      - 14.ARM处理器核系列介绍: notes/College 3/1.嵌入式系统/自己笔记/14-ARM处理器核系列介绍.md
      - 16.存储器管理单元及保护单元: notes/College 3/1.嵌入式系统/自己笔记/16-存储器管理单元及保护单元.md
      - 操作系统: notes/College 3/1.嵌入式系统/自己笔记/OS.md
      - Linux 线程编程: notes/College 3/1.嵌入式系统/自己笔记/Thread_program.md

    - 高级程序设计: 
      - indices/College3/Advanced_Program_Design/index.md
      - Java 学习路线: notes/College 3/1.高级程序设计/期末复习/Java学习路线.md
      - Java 语法:
        - Java 基础语法: notes/College 3/1.高级程序设计/期末复习/Java基础语法.md
        - Java 变量类型: notes/College 3/1.高级程序设计/期末复习/Java变量类型.md
        - Java 数据类型: notes/College 3/1.高级程序设计/期末复习/Java数据类型结构.md
      - Java 面向对象: 
        - Java 继承与多态: notes/College 3/1.高级程序设计/期末复习/Java继承与多态.md
        - Java 包: notes/College 3/1.高级程序设计/期末复习/Java包.md
        - Java 数据管理的类: notes/College 3/1.高级程序设计/期末复习/Java-管理数据的类.md
        - Java 静态类: notes/College 3/1.高级程序设计/期末复习/Java静态类与方法.md
      - Java 设计模式: 
        - Java 设计模式: notes/College 3/1.高级程序设计/期末复习/Java设计模式.md
        - Java 测试驱动: notes/College 3/1.高级程序设计/期末复习/Java-写入一个程序.md
      - Java 正则: 
        - Java 正则表达式: notes/College 3/1.高级程序设计/期末复习/Java-正则表达式.md
        - Java 正则语法: notes/College 3/1.高级程序设计/期末复习/Java-正则语法.md
        - 正则表达式: notes/College 3/1.高级程序设计/期末复习/new_regex.html
      - 其他:
        - Java与python: notes/College 3/1.高级程序设计/期末复习/Java与python.md
        - 测试驱动开发: notes/College 3/1.高级程序设计/期末复习/Java-写入一个程序.md
        - Web 开发: notes/College 3/1.高级程序设计/期末复习/Web开发.html
        - exam: notes/College 3/1.高级程序设计/期末复习/exam.md

    - 误差理论与数据处理: 
      - indices/College3/Error Theory/index.md
      - 1.误差的基本概念: notes/College 3/1.误差理论和数据处理/期末复习/1-误差的基本概念.md
      - 2.误差的基本性质与处理: notes/College 3/1.误差理论和数据处理/期末复习/2-误差的基本性质与处理.md
      - 3.误差的合成与分配: notes/College 3/1.误差理论和数据处理/期末复习/3-误差的合成与分配.md
      - 4.测量不确定度: notes/College 3/1.误差理论和数据处理/期末复习/4-测量不确定度.md
      - 5.最小二乘法: notes/College 3/1.误差理论和数据处理/期末复习/5-线性测量参数的最小二乘法处理.md
      - 6.回归分析: notes/College 3/1.误差理论和数据处理/期末复习/6-回归分析.md
      - 7.动态测试: notes/College 3/1.误差理论和数据处理/期末复习/7-动态测试.md

    - 生物医学图像处理:
      - 1.绪论: notes/College 3/2.生物医学图像处理/期末复习/Lecture1.md
      - 2.图像处理基础: notes/College 3/2.生物医学图像处理/期末复习/Lecture2.md
      - 3.图像变换: notes/College 3/2.生物医学图像处理/期末复习/Lecture3.md
      - 4.时域滤波器设计: notes/College 3/2.生物医学图像处理/期末复习/Lecture4.md
      - 5.图像的 Fourier 变换: notes/College 3/2.生物医学图像处理/期末复习/Lecture5.md
      - 6.频域滤波: notes/College 3/2.生物医学图像处理/期末复习/Lecture6.md
      - 7.图像重建: notes/College 3/2.生物医学图像处理/期末复习/Lecture7.md
      
  - 🔍科研经历:
    - research/index.md

  - 🔗友情链接: 
    - link/index.md    

  - 🗃️杂项: 
    - indices/miscellaneous/index.md
    - 更新记录: changelog.md
    - 样式参考: Miscellaneous/style.md
    - 建档指南: 
      - indices/Site_Instruction/index.md
      - 参考资料: Site Instruction/referrence.md
      - 仓库链接: Site Instruction/仓库链接.md 
    - Career Planning:
      - indices/miscellaneous/career_planning/index.md
      - selected graduates: Miscellaneous/Selected_Student.md
    - 查老师: Miscellaneous/chalaoshi/chalaoshi.md
    - English_Grade: Miscellaneous/English_Grade/README.md

  - 🛫导航: Navigation/navigation.md
  
  - 🛠️实用工具:
    - indices/Tools/index.md
    
  - 🔦个人生活: https://blog-of-eden.vercel.app/

  
